# Team Members Names:
        1. Achyuth Reddy Kanumanthu (11664532)
        2. Yuvaraj Sriramoju(11710243)

#                              KNN Model For Digit recognition

In [6]:
import numpy as np
from sklearn import datasets
import math
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from warnings import filterwarnings
filterwarnings("ignore")


In [7]:
# Load data

data = datasets.load_digits()
data_images=data.images.reshape((len(data.images), -1))
data_target=data.target

final_data=np.insert(data_images,8,data_target,axis=1)
train,test= train_test_split(final_data,test_size=0.5, shuffle=False)

In [3]:
def knn_model(X, y, K_num):
    distance_btw_x_y = list()
    data_X = []
    # Calculating Euclidean  Distance
    for i in X:
        dist=0
        for ab in range(len(y) -1):
            dist=(dist+(y[ab] - i[ab])**2) # Ecl_distance 
        dist = math.sqrt(dist)
        distance_btw_x_y.append(dist)
        data_X.append(i)
    distance = np.array(distance_btw_x_y)
    data_X = np.array(data_X)
    index_dist = distance.argsort()
    data_X = data_X[index_dist]
    knn_neigh_list = data_X[:K_num]
    
    # Classification of Number
    Classes = []
    for i in knn_neigh_list:
        Classes.append(i[-1])
    prediction = max(Classes, key= Classes.count)

    return prediction

In [4]:
acc_table=pd.DataFrame(columns=['K_Value','Accuracy'])
for k_value in [1,3,5,10, 100,500] :
    y_pred = []
    y_true = test[:, -1]
    for i in test:
        prediction = knn_model(train, i, k_value)
        y_pred.append(prediction)
    acc=0
    for ac in range(len(y_true)):
        if y_pred[ac] == y_true[ac]:
            acc=acc+1
    acc=np.round((acc/len(y_true))*100,3)
    print("K Value :",k_value,"and Accuracy:",acc)
    print(confusion_matrix(y_true,y_pred))
    acc_table= acc_table._append({"K_Value":k_value,"Accuracy":acc},ignore_index=True)

print(acc_table)

K Value : 1 and Accuracy: 92.77
[[828   2   0   0   0   0   1   1   0   0   0   0   0   0   0   0   0]
 [ 17   2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  4   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  4   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1   0   1   0   0   0   1   1   0   1   0   0   0   0   0   0   0]
 [  2   0   2   0   0   0   0   1   0   0   0   0   0   0   0   0   0]
 [  1   1   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   0]
 [  1   0   0   0   0   0   0   0   0   1   0   1   0   0   0   0   0]
 [  0   0   0   0   0   0   0   1   0   1   0   0   0   0   0   0   0]
 [  0   0   1   0   0   0   1   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   1   1   0   0   1   0   1   0   0   0   0   0]
 [  0   0   0   0   0   1   0   1   0   0   0